# Generated by Django 3.2.9 on 2021-11-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogInfo', '0004_appointments_dogappointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='activity',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
