# Generated by Django 3.2.9 on 2021-11-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogInfo', '0006_alter_appointments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
