# Generated by Django 3.2.9 on 2021-11-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogInfo', '0008_alter_dog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dog',
            name='birthday',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
